# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
admins:
    path: /{resource}{slash}
    requirements:
        resource: "admins"
        slash: "[/]{0,1}"
    methods: [GET, POST, DELETE, PUT]

policy:
    path: /{resource}{slash}
    requirements:
        resource: "policy"
        slash: "[/]{0,1}"
    methods: [GET, POST, DELETE, PUT]

statistics:
    path: /{resource}{slash}
    requirements:
        resource: "statistics"
        slash: "[/]{0,1}"
    methods: [GET]

monolog:
    path: /{resource}{slash}{action}
    requirements:
        resource: "monolog"
        slash: "[/]{0,1}"
    methods: [GET, DELETE, POST, PUT]

language:
    path: /{resource}{slash}
    requirements:
        resource: "language"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

apps:
    path: /{resource}{slash}
    requirements:
        resource: "apps"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

packages:
    path: /{resource}{slash}
    requirements:
        resource: "packages"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

packagesaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "packages"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

workoutplans:
    path: /{resource}{slash}
    requirements:
        resource: "workoutplans"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

workoutplansaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "workoutplans"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

nutritionplans:
    path: /{resource}{slash}
    requirements:
        resource: "nutritionplans"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

nutritionplansaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "nutritionplans"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

workouts:
    path: /{resource}{slash}
    requirements:
        resource: "workouts"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

workoutsaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "workouts"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

exercises:
    path: /{resource}{slash}
    requirements:
        resource: "exercises"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

exercisesaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "exercises"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

tags:
    path: /{resource}{slash}
    requirements:
        resource: "tags"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

tagsaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "tags"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

recepies:
    path: /{resource}{slash}
    requirements:
        resource: "recepies"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

recepiesaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "recepies"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

users:
    path: /{resource}{slash}
    requirements:
        resource: "users"
        slash: "[/]{0,1}"
    methods: [GET, PUT, POST, DELETE]

notification:
    path: /{resource}{slash}
    requirements:
        resource: "notification"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]

login:
    path: /{resource}{slash}
    requirements:
        resource: "login"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]
